import { createContext, useState, useContext, useEffect } from 'react';

const translations = {
  en: {
    home: "Home",
    about: "About",
    help: "Help",
    login: "Login",
    signup: "Sign Up",
    findScheme: "Find the right scheme for you",
    searchPlaceholder: "Search by scheme name...",
    allCategories: "All Categories",
    featuredSchemes: "Featured Schemes",
    noSchemes: "No schemes found.",
    adjustFilters: "Try adjusting your filters or search term.",
    checkCropHealth: "🌿 Check Your Crop Health",
    uploadImage: "Upload Image",
    analyze: "Analyze",
    aiConfidence: "AI Confidence Score",
    diseaseName: "Disease Name",
    cause: "Cause",
    solution: "Solution",
    disclaimer: "This is an AI-based prediction. Please consult an agricultural expert for final confirmation.",
    analyzing: "Analyzing image with AI...",
    selectImageFirst: "Please select an image first.",
    viewDetails: "View Details",
    appTitle: "Smart Krishi Sahayak",
    appSubtitle: "Farmer Assistance Portal",
    logout: "Logout",
    recommendedForYou: "Recommended for You",
    match: "MATCH",
    subsidy: "Subsidy",
    insurance: "Insurance",
    loan: "Loan",
    soil: "Soil Health",
    "प्रधान मंत्री किसान सम्मान निधि (PM-KISAN)": "PM Kisan Samman Nidhi (PM-KISAN)",
    "₹6,000 per year transferred directly to the bank accounts of farmer families.": "₹6,000 per year transferred directly to the bank accounts of farmer families.",
    "Pradhan Mantri Fasal Bima Yojana (PMFBY)": "Pradhan Mantri Fasal Bima Yojana (PMFBY)",
    "Comprehensive risk insurance to cover yield losses from pre-sowing to post-harvest.": "Comprehensive risk insurance to cover yield losses from pre-sowing to post-harvest.",
    "Soil Health Card Scheme": "Soil Health Card Scheme",
    "Reduces cost of farming by avoiding over-use of fertilizers. Increases yield through optimal nutrient management.": "Reduces cost of farming by avoiding over-use of fertilizers. Increases yield through optimal nutrient management.",
    "Kisan Credit Card (KCC)": "Kisan Credit Card (KCC)",
    "Credit to meet the short term credit requirements for cultivation of crops, post-harvest expenses, produce marketing loan, etc.": "Credit to meet the short term credit requirements for cultivation of crops, post-harvest expenses, produce marketing loan, etc.",
    uploadPhotoPrompt: "Upload a photo of your affected crop leaf to analyze diseases instantly.",
    fileFormatInfo: "PNG, JPG up to 5MB",
    uploadTipsTitle: "Photo Upload Tips",
    tipLighting: "Natural Daylight",
    tipLightingDesc: "Use bright, natural light. Avoid heavy shadows.",
    tipFocus: "Sharp Focus",
    tipFocusDesc: "Ensure the leaf is clear and not blurry.",
    tipDistance: "Optimal Distance",
    tipDistanceDesc: "Keep the camera 10–15cm from the leaf.",
    precautions: "Best Precautions & Steps",
    listening: "Listening...",
    processing: "Processing with Retell AI...",
    tapToSpeak: "Tap to Speak",
    aiResponse: "AI Response",
    voiceAssistantTitle: "Krishi Voice AI",
    onboardingTitle: "Tell us about yourself",
    onboardingSubtitle: "This helps us show you relevant government schemes.",
    roleFarmerSmall: "Small Scale Farmer",
    roleFarmerLarge: "Large Scale Farmer",
    roleDealer: "Dealer / Trader",
    interestsTitle: "What are you looking for?",
    interestsSubtitle: "Select all that apply to personalize your dashboard.",
    interestLoan: "Loans & Credit",
    interestInsurance: "Crop Insurance",
    interestSubsidy: "Subsidies",
    interestSoil: "Soil & Health",
    step: "Step",
    nextStep: "Next Step",
    back: "Back",
    completeSetup: "Complete Setup",
    aboutScheme: "About the Scheme",
    keyBenefits: "Key Benefits",
    eligibility: "Eligibility",
    requiredDocuments: "Required Documents",
    applyNow: "Apply Now",
    findCenter: "Find Application Center",
    backToList: "Back to list",
    schemeNotFound: "Scheme not found",
    returnHome: "Return to Home"
  },
  hi: {
    home: "मुख्य पृष्ठ",
    about: "हमारे बारे में",
    help: "सहायता",
    login: "लॉग इन",
    signup: "साइन अप",
    findScheme: "अपने लिए सही योजना खोजें",
    searchPlaceholder: "योजना के नाम से खोजें...",
    allCategories: "सभी श्रेणियाँ",
    featuredSchemes: "प्रमुख योजनाएं",
    noSchemes: "कोई योजना नहीं मिली।",
    adjustFilters: "फ़िल्टर या खोज शब्द को बदलने का प्रयास करें।",
    checkCropHealth: "🌿 अपनी फसल के स्वास्थ्य की जाँच करें",
    uploadImage: "छवि अपलोड करें",
    analyze: "विश्लेषण करें",
    aiConfidence: "AI आत्मविश्वास अंक",
    diseaseName: "रोग का नाम",
    cause: "कारण",
    solution: "समाधान",
    disclaimer: "यह एक AI-आधारित भविष्यवाणी है। कृपया कृषि विशेषज्ञ से सलाह लें।",
    analyzing: "AI छवि का विश्लेषण कर रहा है...",
    selectImageFirst: "कृपया पहले एक छवि चुनें।",
    viewDetails: "विवरण देखें",
    appTitle: "स्मार्ट कृषि सहायक",
    appSubtitle: "किसान सहायता पोर्टल",
    logout: "लॉग आउट",
    recommendedForYou: "आपके लिए अनुशंसित",
    match: "मेल",
    subsidy: "सब्सिडी",
    insurance: "बीमा",
    loan: "ऋण",
    soil: "मृदा स्वास्थ्य",
    "प्रधान मंत्री किसान सम्मान निधि (PM-KISAN)": "प्रधान मंत्री किसान सम्मान निधि (PM-KISAN)",
    "₹6,000 per year transferred directly to the bank accounts of farmer families.": "किसान परिवारों के बैंक खातों में प्रति वर्ष ₹6,000 सीधे स्थानांतरित किए जाते हैं।",
    "Pradhan Mantri Fasal Bima Yojana (PMFBY)": "प्रधानमंत्री फसल बीमा योजना (PMFBY)",
    "Comprehensive risk insurance to cover yield losses from pre-sowing to post-harvest.": "बुवाई से लेकर फसल कटाई तक उपज के नुकसान को कवर करने के लिए व्यापक जोखिम बीमा।",
    "Soil Health Card Scheme": "मृदा स्वास्थ्य कार्ड योजना",
    "Reduces cost of farming by avoiding over-use of fertilizers. Increases yield through optimal nutrient management.": "उर्वरकों के अत्यधिक उपयोग से बचकर खेती की लागत को कम करता है। इष्टतम पोषक तत्व प्रबंधन के माध्यम से उपज बढ़ाता है।",
    "Kisan Credit Card (KCC)": "किसान क्रेडिट कार्ड (KCC)",
    "Credit to meet the short term credit requirements for cultivation of crops, post-harvest expenses, produce marketing loan, etc.": "फसलों की खेती, फसल कटाई के बाद के खर्च, उपज विपणन ऋण आदि के लिए अल्पकालिक आवश्यकताओं को पूरा करने हेतु ऋण।",
    uploadPhotoPrompt: "रोगों का तुरंत विश्लेषण करने के लिए अपनी प्रभावित फसल की पत्ती की एक फोटो अपलोड करें।",
    fileFormatInfo: "PNG, JPG 5MB तक",
    uploadTipsTitle: "फोटो अपलोड करने के टिप्स",
    tipLighting: "प्राकृतिक रोशनी",
    tipLightingDesc: "तेज, प्राकृतिक रोशनी का उपयोग करें। गहरी छाया से बचें।",
    tipFocus: "स्पष्ट फोकस",
    tipFocusDesc: "सुनिश्चित करें कि पत्ती स्पष्ट है और धुंधली नहीं है।",
    tipDistance: "इष्टतम दूरी",
    tipDistanceDesc: "कैमरे को पत्ती से 10-15 सेमी दूर रखें।",
    precautions: "सर्वोत्तम सावधानियां और कदम",
    listening: "सुन रहा हूँ...",
    processing: "Retell AI के साथ प्रोसेस कर रहा है...",
    tapToSpeak: "बोलने के लिए टैप करें",
    aiResponse: "AI का जवाब",
    voiceAssistantTitle: "कृषि वॉयस AI",
    onboardingTitle: "अपने बारे में हमें बताएं",
    onboardingSubtitle: "यह हमें आपको प्रासंगिक सरकारी योजनाएं दिखाने में मदद करता है।",
    roleFarmerSmall: "छोटे स्तर के किसान",
    roleFarmerLarge: "बड़े स्तर के किसान",
    roleDealer: "डीलर / व्यापारी",
    interestsTitle: "आप क्या ढूंढ रहे हैं?",
    interestsSubtitle: "अपने डैशबोर्ड को वैयक्तिकृत करने के लिए वे सभी चुनें जो लागू हों।",
    interestLoan: "ऋण और क्रेडिट",
    interestInsurance: "फसल बीमा",
    interestSubsidy: "सब्सिडी",
    interestSoil: "मिट्टी और स्वास्थ्य",
    step: "चरण",
    nextStep: "अगला चरण",
    back: "पीछे",
    completeSetup: "सेटअप पूरा करें",
    aboutScheme: "योजना के बारे में",
    keyBenefits: "प्रमुख लाभ",
    eligibility: "पात्रता",
    requiredDocuments: "आवश्यक दस्तावेज़",
    applyNow: "अभी आवेदन करें",
    findCenter: "आवेदन केंद्र खोजें",
    backToList: "सूची पर वापस जाएं",
    schemeNotFound: "योजना नहीं मिली",
    returnHome: "होम पर वापस जाएं"
  },
  mr: {
    home: "मुख्य पृष्ठ",
    about: "आमच्याबद्दल",
    help: "मदत",
    login: "लॉग इन",
    signup: "साइन अप",
    findScheme: "आपल्यासाठी योग्य योजना शोधा",
    searchPlaceholder: "योजनेच्या नावाने शोधा...",
    allCategories: "सर्व श्रेणी",
    featuredSchemes: "वैशिष्ट्यीकृत योजना",
    noSchemes: "कोणत्याही योजना आढळल्या नाहीत.",
    adjustFilters: "आपले फिल्टर किंवा शोध शब्द बदलून पहा.",
    checkCropHealth: "🌿 पीक आरोग्याची तपासणी करा",
    uploadImage: "प्रतिमा अपलोड करा",
    analyze: "विश्लेषण करा",
    aiConfidence: "AI अचूकता स्कोअर",
    diseaseName: "रोगाचे नाव",
    cause: "कारण",
    solution: "उपाय",
    disclaimer: "हा AI-आधारित अंदाज आहे. कृपया कृषी तज्ञाचा सल्ला घ्या.",
    analyzing: "प्रतिमेचे विश्लेषण करत आहे...",
    selectImageFirst: "कृपया प्रथम प्रतिमा निवडा.",
    viewDetails: "तपशील पहा",
    appTitle: "स्मार्ट कृषी सहाय्यक",
    appSubtitle: "शेतकरी मदत पोर्टल",
    logout: "लॉग आउट",
    recommendedForYou: "तुमच्यासाठी शिफारस केलेले",
    match: "साम्य",
    subsidy: "अनुदान",
    insurance: "विमा",
    loan: "कर्ज",
    soil: "मातीचे आरोग्य",
    "प्रधान मंत्री किसान सम्मान निधि (PM-KISAN)": "प्रधान मंत्री किसान सन्मान निधी (PM-KISAN)",
    "₹6,000 per year transferred directly to the bank accounts of farmer families.": "शेतकरी कुटुंबांच्या बँक खात्यात दरवर्षी ₹6,000 थेट जमा केले जातात.",
    "Pradhan Mantri Fasal Bima Yojana (PMFBY)": "प्रधानमंत्री पीक विमा योजना (PMFBY)",
    "Comprehensive risk insurance to cover yield losses from pre-sowing to post-harvest.": "पेरणीपासून काढणीपर्यंतच्या पिकांच्या नुकसानीला कव्हर करणारा सर्वसमावेशक जोखीम विमा.",
    "Soil Health Card Scheme": "मृदा आरोग्य कार्ड योजना",
    "Reduces cost of farming by avoiding over-use of fertilizers. Increases yield through optimal nutrient management.": "खतांचा अतिवापर टाळून शेतीचा खर्च कमी करते. सर्वोत्तम पोषक व्यवस्थापनाद्वारे उत्पादन वाढवते.",
    "Kisan Credit Card (KCC)": "किसान क्रेडिट कार्ड (KCC)",
    "Credit to meet the short term credit requirements for cultivation of crops, post-harvest expenses, produce marketing loan, etc.": "पिकांच्या लागवडीसाठी, काढणीनंतरच्या खर्चासाठी, उत्पादनाच्या विपणन कर्जासाठी यासारख्या अल्पकालीन कर्जाच्या गरजा पूर्ण करण्यासाठी.",
    uploadPhotoPrompt: "रोगांचे त्वरित विश्लेषण करण्यासाठी तुमच्या बाधित पिकाच्या पानाचा फोटो अपलोड करा.",
    fileFormatInfo: "PNG, JPG 5MB पर्यंत",
    uploadTipsTitle: "फोटो अपलोड करण्याच्या टिप्स",
    tipLighting: "नैसर्गिक प्रकाश",
    tipLightingDesc: "भरपूर नैसर्गिक प्रकाशाचा वापर करा. गडद सावल्या टाळा.",
    tipFocus: "स्पष्ट फोकस",
    tipFocusDesc: "पान स्पष्ट आहे आणि अस्पष्ट नाही याची खात्री करा.",
    tipDistance: "योग्य अंतर",
    tipDistanceDesc: "कॅमेरा पानापासून १०-१५ सेमी लांब ठेवा.",
    precautions: "सर्वोत्तम खबरदारी आणि पावले",
    listening: "ऐकत आहे...",
    processing: "Retell AI सह प्रक्रिया करत आहे...",
    tapToSpeak: "बोलण्यासाठी टॅप करा",
    aiResponse: "AI चे उत्तर",
    voiceAssistantTitle: "कृषी वॉयस AI",
    onboardingTitle: "तुमच्याबद्दल आम्हाला सांगा",
    onboardingSubtitle: "हे आम्हाला तुम्हाला संबंधित सरकारी योजना दाखवण्यास मदत करते.",
    roleFarmerSmall: "लहान शेतकरी",
    roleFarmerLarge: "मोठा शेतकरी",
    roleDealer: "डीलर / व्यापारी",
    interestsTitle: "तुम्ही काय शोधत आहात?",
    interestsSubtitle: "तुमचा डॅशबोर्ड वैयक्तिकृत करण्यासाठी लागू होणारे सर्व निवडा.",
    interestLoan: "कर्ज आणि क्रेडिट",
    interestInsurance: "पीक विमा",
    interestSubsidy: "अनुदान",
    interestSoil: "माती आणि आरोग्य",
    step: "पाऊल",
    nextStep: "पुढील पाऊल",
    back: "मागे",
    completeSetup: "सेटअप पूर्ण करा",
    aboutScheme: "योजनेबद्दल",
    keyBenefits: "प्रमुख फायदे",
    eligibility: "पात्रता",
    requiredDocuments: "आवश्यक कागदपत्रे",
    applyNow: "आता अर्ज करा",
    findCenter: "अर्ज केंद्र शोधा",
    backToList: "सूचीवर परत जा",
    schemeNotFound: "योजना आढळली नाही",
    returnHome: "मुख्यपृष्ठावर परत जा"
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('appLang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('appLang', language);
  }, [language]);

  const t = (key) => {
    // Return key if not found, to support DB strings pass-through if missing
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
