# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v6-pIwUmve0MP9m_xr8jLmnAMjtGE-W0
"""

import torch

print("GPU available:", torch.cuda.is_available())
print("GPU name:", torch.cuda.get_device_name(0))
print("PyTorch version:", torch.__version__)

# Step 1: Upload your kaggle.json file
from google.colab import files
files.upload()   # click "Choose Files" → select your kaggle.json

# Step 2: Move it to the right location
import os
os.makedirs('/root/.kaggle', exist_ok=True)
os.rename('kaggle.json', '/root/.kaggle/kaggle.json')
os.chmod('/root/.kaggle/kaggle.json', 600)

# Step 3: Install kaggle library
!pip install kaggle -q

print("Kaggle API ready!")

# Download the dataset (takes 2-3 minutes)
!kaggle datasets download -d vipoooool/new-plant-diseases-dataset

# Unzip it
import zipfile
with zipfile.ZipFile('new-plant-diseases-dataset.zip', 'r') as z:
    z.extractall('plant_disease_data')

print("Dataset downloaded and unzipped!")

# Check the folder structure
import os
train_path = 'plant_disease_data/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/train'
classes = os.listdir(train_path)
print(f"Total disease classes: {len(classes)}")
print("Sample classes:", classes[:5])

import torch
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

# Image transformations
train_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(),      # data augmentation
    transforms.RandomRotation(10),          # slight rotation
    transforms.ColorJitter(brightness=0.2), # vary brightness
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

val_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

# Load datasets
train_path = 'plant_disease_data/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/train'
val_path   = 'plant_disease_data/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/valid'

train_data = datasets.ImageFolder(train_path, transform=train_transform)
val_data   = datasets.ImageFolder(val_path,   transform=val_transform)

# Create loaders
train_loader = DataLoader(train_data, batch_size=32, shuffle=True,  num_workers=2)
val_loader   = DataLoader(val_data,   batch_size=32, shuffle=False, num_workers=2)

print(f"Training images  : {len(train_data)}")
print(f"Validation images: {len(val_data)}")
print(f"Disease classes  : {len(train_data.classes)}")

import torch.nn as nn
from torchvision import models

# Load ResNet50 pretrained on ImageNet
model = models.resnet50(weights='IMAGENET1K_V1')

# Freeze all existing layers — keep their knowledge
for param in model.parameters():
    param.requires_grad = False

# Replace the final classification layer
num_classes = len(train_data.classes)  # 38 for PlantVillage
model.fc = nn.Sequential(
    nn.Linear(model.fc.in_features, 512),
    nn.ReLU(),
    nn.Dropout(0.3),
    nn.Linear(512, num_classes)
)

# Move to GPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = model.to(device)

print(f"Model ready on: {device}")
print(f"Training for {num_classes} disease classes")

import torch.nn as nn
import torch.optim as optim
from torch.optim import lr_scheduler

# Loss function
criterion = nn.CrossEntropyLoss()

# Optimizer (only update the new classification layer)
optimizer = optim.Adam(model.fc.parameters(), lr=0.001)

# Learning rate scheduler
scheduler = lr_scheduler.StepLR(optimizer, step_size=7, gamma=0.1)

print("Criterion, Optimizer, and Scheduler defined.")

import time
import copy

def train_model(model, criterion, optimizer, scheduler, num_epochs=10):
    since = time.time()

    best_model_wts = copy.deepcopy(model.state_dict())
    best_acc = 0.0

    for epoch in range(num_epochs):
        print(f'Epoch {epoch}/{num_epochs - 1}')
        print('-' * 10)

        # Each epoch has a training and validation phase
        for phase in ['train', 'val']:
            if phase == 'train':
                model.train()  # Set model to training mode
            else:
                model.eval()   # Set model to evaluate mode

            running_loss = 0.0
            running_corrects = 0

            # Iterate over data.
            dataloader = train_loader if phase == 'train' else val_loader
            for inputs, labels in dataloader:
                inputs = inputs.to(device)
                labels = labels.to(device)

                # zero the parameter gradients
                optimizer.zero_grad()

                # forward
                # track history if only in train
                with torch.set_grad_enabled(phase == 'train'):
                    outputs = model(inputs)
                    _, preds = torch.max(outputs, 1)
                    loss = criterion(outputs, labels)

                    # backward + optimize only if in training phase
                    if phase == 'train':
                        loss.backward()
                        optimizer.step()

                # statistics
                running_loss += loss.item() * inputs.size(0)
                running_corrects += torch.sum(preds == labels.data)
            if phase == 'train':
                scheduler.step()

            epoch_loss = running_loss / len(dataloader.dataset)
            epoch_acc = running_corrects.double() / len(dataloader.dataset)

            print(f'{phase} Loss: {epoch_loss:.4f} Acc: {epoch_acc:.4f}')

            # deep copy the model if it's the best validation accuracy
            if phase == 'val' and epoch_acc > best_acc:
                best_acc = epoch_acc
                best_model_wts = copy.deepcopy(model.state_dict())

        print()

    time_elapsed = time.time() - since
    print(f'Training complete in {time_elapsed // 60:.0f}m {time_elapsed % 60:.0f}s')
    print(f'Best val Acc: {best_acc:4f}')

    # load best model weights
    model.load_state_dict(best_model_wts)
    return model

# Start training
model = train_model(model, criterion, optimizer, scheduler, num_epochs=5) # Reduced epochs for faster execution

print("Model training complete.")

import torch.optim as optim

criterion = nn.CrossEntropyLoss()

# Only train the new layers we added
optimizer = optim.Adam(model.fc.parameters(), lr=0.001)

# Reduce learning rate when val accuracy stops improving
scheduler = optim.lr_scheduler.ReduceLROnPlateau(
    optimizer, mode='max', patience=2, factor=0.5
)

print("Optimizer and scheduler ready")

import torch.optim as optim
import torch.nn as nn
from torchvision import models, datasets, transforms
from torch.utils.data import DataLoader
import torch
import os
import zipfile

# --- Dataset Setup ---
dataset_zip = 'new-plant-diseases-dataset.zip'
dataset_folder = 'plant_disease_data'

if not os.path.exists(dataset_folder):
    print("Downloading and unzipping dataset...")
    !kaggle datasets download -d vipoooool/new-plant-diseases-dataset
    with zipfile.ZipFile(dataset_zip, 'r') as z:
        z.extractall(dataset_folder)

# --- Data Loaders (Global) ---
train_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

val_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

train_path = 'plant_disease_data/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/train'
val_path = 'plant_disease_data/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/valid'

train_data = datasets.ImageFolder(train_path, transform=train_transform)
val_data = datasets.ImageFolder(val_path, transform=val_transform)

train_loader = DataLoader(train_data, batch_size=32, shuffle=True, num_workers=2)
val_loader = DataLoader(val_data, batch_size=32, shuffle=False, num_workers=2)

# --- Model Setup ---
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = models.resnet50(weights='IMAGENET1K_V1')
for param in model.parameters():
    param.requires_grad = False

model.fc = nn.Sequential(
    nn.Linear(model.fc.in_features, 512),
    nn.ReLU(),
    nn.Dropout(0.3),
    nn.Linear(512, len(train_data.classes))
)
model = model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.fc.parameters(), lr=0.001)
scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='max', patience=2, factor=0.5)

def train_model(epochs=10):
    best_acc = 0
    for epoch in range(epochs):
        model.train()
        for images, labels in train_loader:
            images, labels = images.to(device), labels.to(device)
            optimizer.zero_grad()
            loss = criterion(model(images), labels)
            loss.backward()
            optimizer.step()

        model.eval()
        vc, vt = 0, 0
        with torch.no_grad():
            for images, labels in val_loader:
                images, labels = images.to(device), labels.to(device)
                out = model(images)
                _, pred = out.max(1)
                vt += labels.size(0)
                vc += pred.eq(labels).sum().item()

        val_acc = 100 * vc / vt
        scheduler.step(val_acc)
        print(f"Epoch {epoch+1}/{epochs} | Val Acc: {val_acc:.1f}%")
        if val_acc > best_acc:
            best_acc = val_acc
            torch.save(model.state_dict(), 'best_model.pth')

# Run training
train_model(epochs=5)

from google.colab import drive
import shutil, json
import os

drive.mount('/content/drive')

model_filename = 'best_model.pth'
class_names_filename = 'class_names.json'

# Try to copy the model file
if os.path.exists(model_filename):
    shutil.copy(model_filename, f'/content/drive/MyDrive/{model_filename}')
    print(f"Model '{model_filename}' saved to Google Drive!")
else:
    print(f"Warning: Model file '{model_filename}' not found. Please ensure the training cell (the one containing the `train_model` function) ran successfully and saved the best model.")

# Try to save class names
try:
    # Check if 'train_data' is globally available and has a 'classes' attribute
    if 'train_data' in globals() and hasattr(train_data, 'classes'):
        with open(f'/content/drive/MyDrive/{class_names_filename}', 'w') as f:
            json.dump(train_data.classes, f)
        print(f"Class names '{class_names_filename}' saved to Google Drive!")
    else:
        print(f"Warning: 'train_data' not found or does not have a 'classes' attribute. Cannot save class names. Please ensure the data loading cell ran successfully.")
except NameError:
    print(f"Warning: 'train_data' is not defined. Cannot save class names. Please ensure the data loading cell ran successfully.")

from PIL import Image
from google.colab import files
import torch
import torch.nn as nn
from torchvision import models, transforms
import json
import os

# 1. Setup Device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# 2. Re-initialize Model Architecture
model = models.resnet50(weights=None)
num_classes = 38 # Standard for this plant disease dataset
model.fc = nn.Sequential(
    nn.Linear(model.fc.in_features, 512),
    nn.ReLU(),
    nn.Dropout(0.3),
    nn.Linear(512, num_classes)
)

# 3. Load Trained Weights
model_path = 'best_model.pth'
if os.path.exists(model_path):
    model.load_state_dict(torch.load(model_path, map_location=device))
    print("Trained model weights loaded.")
else:
    print("Warning: best_model.pth not found. Using uninitialized model. Please ensure training finished.")

model = model.to(device)
model.eval()

# 4. Upload and Transform Image
uploaded = files.upload()
if uploaded:
    img_path = list(uploaded.keys())[0]

    test_transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])

    def predict(image_path):
        img = Image.open(image_path).convert('RGB')
        tensor = test_transform(img).unsqueeze(0).to(device)

        with torch.no_grad():
            output = model(tensor)
            probs = torch.nn.functional.softmax(output[0], dim=0)

        top3_probs, top3_idx = torch.topk(probs, 3)

        # Try to get class names from train_data if available, else use indices
        print("\nTop 3 predictions:")
        print("-" * 40)
        for i in range(3):
            idx = top3_idx[i].item()
            label = train_data.classes[idx] if 'train_data' in globals() else f"Class ID: {idx}"
            confidence = top3_probs[i].item() * 100
            print(f"{i+1}. {label}")
            print(f"   Confidence: {confidence:.1f}%")

    predict(img_path)

from sklearn.metrics import classification_report
import numpy as np
import torch

# Ensure we use the correct device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.to(device)
model.eval()

all_preds = []
all_labels = []

# Check if val_loader exists, if not, we'll need to use the one from the training setup
current_val_loader = globals().get('val_loader')

if current_val_loader is None:
    print("Error: 'val_loader' not found. Please ensure the data loading cell (PiY12K0j4RWa) has been executed.")
else:
    print("Running evaluation on validation set...")
    with torch.no_grad():
        for images, labels in current_val_loader:
            images = images.to(device)
            outputs = model(images)
            _, predicted = outputs.max(1)
            all_preds.extend(predicted.cpu().numpy())
            all_labels.extend(labels.numpy())

    # Overall accuracy
    all_preds = np.array(all_preds)
    all_labels = np.array(all_labels)
    correct = np.sum(all_preds == all_labels)
    total = len(all_labels)

    print(f"Overall Accuracy: {100 * correct / total:.2f}%")
    print(f"Correct: {correct} / {total}")

    # Per-disease accuracy breakdown
    if 'train_data' in globals():
        print("\nPer-disease breakdown:")
        print(classification_report(
            all_labels, all_preds,
            target_names=train_data.classes,
            digits=2
        ))
    else:
        print("\nClassification report (Indices only - train_data.classes not found):")
        print(classification_report(all_labels, all_preds, digits=2))

def predict_with_threshold(image_path, threshold=60.0):
    img = Image.open(image_path).convert('RGB')
    tensor = test_transform(img).unsqueeze(0).to(device)

    model.eval()
    with torch.no_grad():
        output = model(tensor)
        probs = torch.nn.functional.softmax(output[0], dim=0)
        confidence, idx = torch.max(probs, 0)

    confidence_pct = confidence.item() * 100
    disease = train_data.classes[idx.item()]

    if confidence_pct < threshold:
        return {
            "status": "unclear",
            "message": "Photo is unclear. Please retake in good lighting.",
            "confidence": f"{confidence_pct:.1f}%"
        }
    else:
        return {
            "status": "detected",
            "disease": disease,
            "confidence": f"{confidence_pct:.1f}%"
        }

from PIL import Image
from google.colab import files
import torch
import torch.nn as nn
from torchvision import models, transforms
import json
import os

# 1. Setup Device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# 2. Re-initialize Model Architecture
model = models.resnet50(weights=None)
num_classes = 38 # Standard for this plant disease dataset
model.fc = nn.Sequential(
    nn.Linear(model.fc.in_features, 512),
    nn.ReLU(),
    nn.Dropout(0.3),
    nn.Linear(512, num_classes)
)

# 3. Load Trained Weights
model_path = 'best_model.pth'
if os.path.exists(model_path):
    model.load_state_dict(torch.load(model_path, map_location=device))
    print("Trained model weights loaded.")
else:
    print("Warning: best_model.pth not found. Using uninitialized model. Please ensure training finished.")

model = model.to(device)
model.eval()

# 4. Upload and Transform Image
uploaded = files.upload()
if uploaded:
    img_path = list(uploaded.keys())[0]

    test_transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])

    def predict(image_path):
        img = Image.open(image_path).convert('RGB')
        tensor = test_transform(img).unsqueeze(0).to(device)

        with torch.no_grad():
            output = model(tensor)
            probs = torch.nn.functional.softmax(output[0], dim=0)

        top3_probs, top3_idx = torch.topk(probs, 3)

        # Try to get class names from train_data if available, else use indices
        print("\nTop 3 predictions:")
        print("-" * 40)
        for i in range(3):
            idx = top3_idx[i].item()
            label = train_data.classes[idx] if 'train_data' in globals() else f"Class ID: {idx}"
            confidence = top3_probs[i].item() * 100
            print(f"{i+1}. {label}")
            print(f"   Confidence: {confidence:.1f}%")

    predict(img_path)